<script setup lang="ts">
import type { components } from "~/api_types";

// The autogenerated name for `pages/view/[id].vue` collides with the one
// for `pages/[view]/[id].vue`; pin a unique name so vue-router can match.
definePageMeta({ name: "view-redirect" });

type LocationDetailsResponse = components["schemas"]["LocationDetailsResponse"];

const route = useRoute();
const localePath = useLocalePath();
const runtimeConfig = useRuntimeConfig();
const { locale } = useI18n();
const id = route.params.id as string;

if (id === "root") {
  await navigateTo(
    { path: localePath("/"), query: route.query },
    { redirectCode: 301, replace: true }
  );
} else {
  const { data, error } = await useFetch<LocationDetailsResponse, string>(
    () => `${runtimeConfig.public.apiURL}/api/locations/${id}?lang=${locale.value}`,
    { dedupe: "cancel", credentials: "omit" }
  );

  if (error.value || !data.value?.redirect_url) {
    showError({ statusCode: 404, statusMessage: "Location not found" });
  } else {
    await navigateTo(
      { path: localePath(data.value.redirect_url), query: route.query },
      { redirectCode: 301, replace: true }
    );
  }
}
</script>

<template>
  <div />
</template>
