apiVersion: apps/v1
kind: Deployment
metadata:
  name: webclient
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: web
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: navigatum
      app.kubernetes.io/name: web
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: navigatum
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: webclient
          image: "ghcr.io/tum-dev/navigatum-webclient:{{ $.Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: webclient
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /health
              port: webclient
            failureThreshold: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: webclient
            failureThreshold: 60
            periodSeconds: 1
