---
- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Install cert-manager
  kubernetes.core.helm:
    atomic: true
    wait: true
    update_repo_cache: yes
    release_state: present
    chart_ref: jetstack/cert-manager
    chart_version: v1.10.0
    name: cert-manager
    namespace: cert-manager
    create_namespace: yes
    values:
      installCRDs: true
      ingressShim:
        defaultIssuerName: letsencrypt-production
        defaultIssuerKind: ClusterIssuer

- name: add letsencrypt-staging ClusterIssuer
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-staging
      spec:
        acme:
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          email: navigatum@tum.de
          privateKeySecretRef:
            name: letsencrypt-account-key-staging
          solvers:
            - http01:
                ingress:
                  class: traefik

- name: add letsencrypt-production ClusterIssuer
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-production
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: navigatum@tum.de
          privateKeySecretRef:
            name: letsencrypt-account-key-production
          solvers:
            - http01:
                ingress:
                  class: traefik
            - dns01:
                cnameStrategy: Follow
                cloudflare:
                  email: my-cloudflare-acc@example.com
                  apiTokenSecretRef:
                    name: cloudflare-api-token-secret
                    key: api-token
                ingress:
                  class: traefik

- name: add selfsigned ClusterIssuer
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned
      spec:
        selfSigned: {}
