---
- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Install longhorn
  kubernetes.core.helm:
    atomic: false
    release_state: present
    wait: false
    chart_ref: longhorn/longhorn
    chart_version: 1.4.1
    name: longhorn
    namespace: longhorn-system
    create_namespace: yes