# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/webclient"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/data"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/data"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/webclient"
    schedule:
      interval: "weekly"
