
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-794
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TUM-Dev/navigatum.git
    targetRevision: renovate/all-minor-patch
    path: deployment/k3s
    helm:
      version: v3
      values: |
        namespace: pr-794
        tag: pr-794
        url: pr-794.nav.tum.sexy
        server:
            MEILI_MASTER_KEY: NzcwNzM3YjhiNjE3OThjY2JkMTcK
            # GITHUB_TOKEN is intentionally omitted, as this file is templated and then added to git in the deployments branch
            # JWT_KEY is omitted, because adding it would only make sense in conjunction with GITHUB_TOKEN
            # MEILI_MASTER_KEY being added is not a security risk, since it is a hidden service and even if exposed is heavily restricted by other network policies
  destination:
    server: https://kubernetes.default.svc
    namespace: pr-794
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
