{{- if eq "nav.tum.de" $.Values.url }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: navigatum
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
{{ end }}
