apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    app: navigatum
    deployment: postgres
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/navigatum/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: navigatum
  labels:
    app: navigatum
    deployment: postgres
    type: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
