// tslint:disable
/**
 * NavigaTUM
 * Navigating around TUM with excellence – An API to search for rooms, buildings and other places  NavigaTUM is a non-official tool developed by students for students, that aims to help you get around at [TUM](https://tum.de). Feel free to contribute.  Features:  - Interactive or RoomFinder-like maps to lookup the position of rooms or buildings - Fast and typo-tolerant search - Support for different room code formats as well as generic names  All functionality is also available via an API.  *Note: Not all buildings in NavigaTUM are owned by TUM, but are instead being used by TUM departments.*
 *
 * OpenAPI spec version: 1.0.0
 * Contact: app@tum.de
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
