---
- name: Add grafana chart repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"

- name: Install promtail
  kubernetes.core.helm:
    atomic: true
    wait: false
    update_repo_cache: yes
    release_state: present
    chart_version: 6.11.1
    chart_ref: grafana/promtail
    name: promtail
    namespace: monitoring
    create_namespace: yes
    values:
      fullnameOverride: promtail

      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      tolerations: []
      serviceMonitor:
        enabled: true
        #prometheusRule:
        #  enabled: true
        #  rules:
        #    - alert: PromtailRequestErrors
        #      expr: 100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[1m])) by (namespace, job, route, instance) / sum(rate(promtail_request_duration_seconds_count[1m])) by (namespace, job, route, instance) > 10
        #      for: 5m
        #      labels:
        #        severity: critical
        #      annotations:
        #        description: |
        #          The {{ $labels.job }} {{ $labels.route }} is experiencing
        #          {{ printf \"%.2f\" $value }} errors.
        #          VALUE = {{ $value }}
        #          LABELS = {{ $labels }}
        #        summary: Promtail request errors (instance {{ $labels.instance }})
        #    - alert: PromtailRequestLatency
        #      expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[5m])) by (le)) > 1
        #      for: 5m
        #      labels:
        #        severity: critical
        #      annotations:
        #        summary: Promtail request latency (instance {{ $labels.instance }})
        #        description: |
        #          The {{ $labels.job }} {{ $labels.route }} is experiencing
        #          {{ printf \"%.2f\" $value }}s 99th percentile latency.
        #          VALUE = {{ $value }}
        #          LABELS = {{ $labels }}
            
      config:
        clients:
          - url: http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push