---
- name: Add prometheus chart repo
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install prometheus-pushgateway
  kubernetes.core.helm:
    atomic: true
    wait: false
    update_repo_cache: yes
    release_state: present
    chart_version: 2.1.3
    chart_ref: prometheus/prometheus-pushgateway
    name: prometheus-pushgateway
    namespace: monitoring
    create_namespace: yes
    values:
      resources:
        limits:
          cpu: 200m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 30Mi
      serviceMonitor:
        enabled: true
      persistentVolume:
        enabled: true
        size: 2Gi
        storageClass: "longhorn"
