---
- name: Install longhorn requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-common
    - open-iscsi
    - bash
    - curl
    - jq
- name: make shure that modules are loaded
  modprobe:
    name: iscsi_tcp
    state: present
