apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  labels:
    app.kubernetes.io/part-of: navigatum
  namespace: {{ $.Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - /maps
