apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nav-tum-de-redirect
  labels:
    app: navigatum
  namespace: {{ .Values.namespace }}
spec:
  redirectRegex:
    regex: "^(https?://.*)nav.tum.(app|sexy)/(.*)$"
    replacement: "${1}nav.tum.de/${3}"
    permanent: true
