# This part is done by the LRZ, whcich is the hoster of the server
# If we were to migrate to another hoster, this would be needed
- name: Install unattended upgrades
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unattended-upgrades
    - apt-listchanges
- name: Configure unattended upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  notify:
    - restart unattended upgrades
