- name: set timezone
  timezone:
    name: Europe/Berlin
- name: set locale
  locale_gen:
    name: en_US.UTF-8
    state: present
- name: set text editor
  alternatives:
    name: editor
    path: /bin/nano
- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

# by default this is configured to get our nodes down at 7 on specific dates, this configures the nodes not to fail all at the same time
- name: Configure lrz-base-automatic-reboot
  template:
    src: lrz-base-automatic-reboot.j2
    dest: /etc/cron.d/lrz-base-automatic-reboot
    owner: root
    group: root
    mode: 0644

- name: Create an user, which can login via SSH to edit a file using rsync, but nothing more
  ansible.builtin.user:
    name: "rbg-rsync"
    create_home: true
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: ".ssh/id_{{ inventory_hostname }}"
    ssh_key_comment: "frank@elsinga.de"
    state: present
    shell: /bin/bash
- name: make shure, that the user can login via SSH
  ansible.builtin.copy:
    remote_src: true
    src: /home/rbg-rsync/.ssh/id_{{ inventory_hostname }}.pub
    dest: /home/rbg-rsync/.ssh/authorized_keys
    owner: rbg-rsync
    group: rbg-rsync
    mode: 0600