- name: Add ssh ports to UFW
  ufw:
    direction: in
    rule: allow
    port: "37670"
    from_ip: "{{ item }}"
    proto: tcp
    comment: SSH from VPN
  loop: "{{ vpn_ips }}"

- name: Enshure, that authorized_keys file has the correct content
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: Enshure sshd is configured correctly
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Remove default ssh port from UFW
  ufw:
    rule: allow
    port: "22"
    proto: tcp
    delete: yes
    from_ip: "{{ item }}"
  loop: "{{ vpn_ips }}"
