FROM getmeili/meilisearch:v1.2.0 as build-stage

RUN apk add --no-cache jq bash

COPY configure_MeileSearch.sh /configure_MeileSearch.sh

# removing the files before and after is nessesary in case the container is restarted
CMD    rm -f *.json \
    && wget https://nav.tum.de/cdn/search_data.json --quiet \
    && wget https://nav.tum.de/cdn/search_synonyms.json --quiet \
    && bash /configure_MeileSearch.sh \
    && rm -f *.json
