apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: cdn
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: navigatum
      app.kubernetes.io/name: cdn
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: navigatum
        app.kubernetes.io/name: cdn
    spec:
      priorityClassName: {{ $.Values.url }}
      containers:
        - name: data
          image: "ghcr.io/tum-dev/navigatum-data:{{ $.Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: cdn
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /cdn/health
              port: cdn
            failureThreshold: 3
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /cdn/health
              port: cdn
            failureThreshold: 60
            periodSeconds: 1
          securityContext:
            capabilities:
              drop:
              - ALL
              add:
              - CHOWN
              - DAC_OVERRIDE
              - SETGID
              - SETUID
