apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: feedback
  namespace: {{ $.Values.namespace }}
spec:
  replicas:  1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: navigatum
      app.kubernetes.io/name: feedback
  strategy:
    rollingUpdate:
      maxSurge: {{ if eq "nav.tum.de" $.Values.url }}50%{{ else }}100%{{ end }}
      maxUnavailable: {{ if eq "nav.tum.de" $.Values.url }}50%{{ else }}0%{{ end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: navigatum
        app.kubernetes.io/name: feedback
      {{- if eq "nav.tum.de" $.Values.url }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '3004'
        prometheus.io/scrape: 'true'
      {{- end }}
    spec:
      priorityClassName: {{ $.Values.url }}
      affinity: # no two pods on the same node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - navigatum
              - key: deployment
                operator: In
                values:
                - feedback
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: feedback
          image: "ghcr.io/tum-dev/navigatum-server:{{ $.Values.tag }}"
          imagePullPolicy: Always
          command: ["/bin/navigatum-feedback"]
          {{ if or (.Values.server.GITHUB_TOKEN) (.Values.server.JWT_KEY) }}
          envFrom:
            - secretRef:
                name: feedback-api-keys # GITHUB_TOKEN, JWT_KEY
          {{ end }}
          ports:
            - containerPort: 3004
              name: feedback
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1m
              memory: 40Mi
            limits:
              memory: 40Mi
          livenessProbe:
            httpGet:
              path: /api/feedback/status
              port: feedback
            failureThreshold: 2
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /api/feedback/status
              port: feedback
            failureThreshold: 6
            periodSeconds: 1
{{ if or (.Values.server.GITHUB_TOKEN) (.Values.server.JWT_KEY) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: feedback-api-keys
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: feedback
data:
  {{ if $.Values.server.GITHUB_TOKEN }}
    GITHUB_TOKEN: {{ $.Values.server.GITHUB_TOKEN }}
  {{ end }}
  {{ if $.Values.server.JWT_KEY }}
    JWT_KEY: {{ $.Values.server.JWT_KEY }}
  {{ end }}
{{ end }}
