apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps
  labels:
    app: navigatum
    deployment: maps
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: navigatum
      deployment: maps
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: navigatum
        deployment: maps
    spec:
      volumes:
        - name: tmp-tileserver
          emptyDir: {}
        - name: tileserver-vol
          persistentVolumeClaim:
              readOnly: false
              claimName: tileserver-pvc
      containers:
        - name: tileserver
          image: maptiler/tileserver-gl:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # changing the public_url also changes this port.
              name: tileserver
          args:
            - --public_url=https://nav.tum.de/maps/ # we want this to live under /maps/
          volumeMounts:
            - mountPath: /tmp
              name: tmp-tileserver
            - mountPath: /data
              name: tileserver-vol
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 30m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 700Mi
          livenessProbe:
            httpGet:
              path: /health
              port: tileserver
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: tileserver
            failureThreshold: 6
            periodSeconds: 10
