kind: ConfigMap
apiVersion: v1
metadata:
  name: tileserver-config
  namespace: {{ $.Values.namespace }}
data:
  osm-liberty.json: |-
{{ .Files.Get "files/osm-liberty.json" | indent 4 }}
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
