apiVersion: v1
kind: PersistentVolume
metadata:
  name: tileserver-pv
  namespace: {{ .Values.namespace }}
  labels:
    app: navigatum
    deployment: maps
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 28Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/navigatum/tileserver"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: navigatum
    deployment: maps
    type: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 28Gi
