apiVersion: v1
kind: PersistentVolume
metadata:
  name: tileserver-{{ $.Values.namespace }}
  labels:
    app: navigatum
    deployment: maps
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 28Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/navigatum/tileserver"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc
  namespace: {{ $.Values.namespace }}
  labels:
    app: navigatum
    deployment: maps
    type: local
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 28Gi
