---
- name: Install cert-manager
  kubernetes.core.helm:
    chart_repo_url: https://charts.jetstack.io
    chart_ref: jetstack/cert-manager
    chart_version: v1.10.0
    release_name: cert-manager
    namespace: cert-manager
    create_namespace: yes
    values:
      installCRDs: true
      ingressShim:
        defaultIssuerName: letsencrypt-prod
        defaultIssuerKind: ClusterIssuer
      clusterIssuers:
        - name: letsencrypt-staging
          acme:
            server: https://acme-staging-v02.api.letsencrypt.org/directory
            email: it-support@tum.de
            privateKeySecretRef:
              name: letsencrypt-account-key-staging
            solvers:
              - http01:
                ingress:
                  class: traefik
        - name: letsencrypt-prod
          acme:
            server: https://acme-v02.api.letsencrypt.org/directory
            email: it-support@tum.de
            privateKeySecretRef:
              name: letsencrypt-account-key-prod
            solvers:
              - http01:
                ingress:
                  class: traefik
        - name: selfsigned
          selfSigned: {}
