apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: api
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: api
  ports:
    - name: mieli-search
      port: 7700
      targetPort: 7700
    - name: api
      port: 7000
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-svc
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: feedback
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: feedback
  ports:
    - name: feedback
      port: 8070
      targetPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-svc
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: calendar
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: calendar
  ports:
    - name: calendar
      port: 8060
      targetPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: maps-svc
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: maps
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: maps
  ports:
    - name: tileserver
      port: 7770
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: cdn
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: cdn
  ports:
    - name: cdn
      port: 8000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webclient-svc
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: web
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: web
  ports:
    - name: webclient
      port: 9000
      targetPort: 80
