-- Add up migration script here
DROP TABLE rooms;

-- migrating to using the json type instead of having elaborate insertion logic
ALTER TABLE de ALTER COLUMN data type jsonb USING data::jsonb;
ALTER TABLE de DROP COLUMN lat;
ALTER TABLE de ADD COLUMN lat FLOAT NOT NULL GENERATED ALWAYS AS (CAST (data->'coords'->>'lat' AS FLOAT)) STORED;
ALTER TABLE de DROP COLUMN lon;
ALTER TABLE de ADD COLUMN lon FLOAT NOT NULL GENERATED ALWAYS AS (CAST (data->'coords'->>'lon' AS FLOAT)) STORED;
ALTER TABLE de DROP COLUMN name;
ALTER TABLE de ADD COLUMN name TEXT NOT NULL GENERATED ALWAYS AS (CAST (data->>'name' AS TEXT)) STORED;
ALTER TABLE de DROP COLUMN type_common_name;
ALTER TABLE de ADD COLUMN type_common_name TEXT NOT NULL GENERATED ALWAYS AS (CAST (data->>'type_common_name' AS TEXT)) STORED;
ALTER TABLE de DROP COLUMN type;
ALTER TABLE de ADD COLUMN type TEXT NOT NULL GENERATED ALWAYS AS (CAST (data->>'type' AS TEXT)) STORED;
ALTER TABLE de ADD COLUMN calendar_url TEXT GENERATED ALWAYS AS (CAST (data->'props'->>'calendar_url' AS TEXT)) STORED;
ALTER TABLE de DROP COLUMN tumonline_room_nr;
ALTER TABLE de ADD COLUMN tumonline_room_nr INTEGER GENERATED ALWAYS AS (CAST (data->'props'->>'tumonline_room_nr' AS INTEGER)) STORED;

ALTER TABLE en ALTER COLUMN data type jsonb USING data::jsonb;
ALTER TABLE en DROP COLUMN lat;
ALTER TABLE en ADD COLUMN lat FLOAT NOT NULL GENERATED ALWAYS AS (CAST (data->'coords'->>'lat' AS FLOAT)) STORED;
ALTER TABLE en DROP COLUMN lon;
ALTER TABLE en ADD COLUMN lon FLOAT NOT NULL GENERATED ALWAYS AS (CAST (data->'coords'->>'lon' AS FLOAT)) STORED;
ALTER TABLE en DROP COLUMN name;
ALTER TABLE en ADD COLUMN name TEXT NOT NULL GENERATED ALWAYS AS (CAST (data->>'name' AS TEXT)) STORED;
ALTER TABLE en DROP COLUMN type_common_name;
ALTER TABLE en ADD COLUMN type_common_name TEXT NOT NULL GENERATED ALWAYS AS (CAST (data->>'type_common_name' AS TEXT)) STORED;
ALTER TABLE en DROP COLUMN type;
ALTER TABLE en ADD COLUMN type TEXT NOT NULL GENERATED ALWAYS AS (CAST (data->>'type' AS TEXT)) STORED;
ALTER TABLE en ADD COLUMN calendar_url TEXT GENERATED ALWAYS AS (CAST (data->'props'->>'calendar_url' AS TEXT)) STORED;
ALTER TABLE en DROP COLUMN tumonline_room_nr;
ALTER TABLE en ADD COLUMN tumonline_room_nr INTEGER GENERATED ALWAYS AS (CAST (data->'props'->>'tumonline_room_nr' AS INTEGER)) STORED;
