apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: navigatum
    deployment: api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: navigatum
    deployment: api
  ports:
    - name: mieli-search
      port: 7700
      targetPort: 7700
    - name: api
      port: 7000
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maps-svc
  labels:
    app: navigatum
    deployment: maps
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: navigatum
    deployment: maps
  ports:
    - name: tileserver
      port: 7770
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
  labels:
    app: navigatum
    deployment: cdn
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: navigatum
    deployment: cdn
  ports:
    - name: cdn
      port: 8000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webclient-svc
  labels:
    app: navigatum
    deployment: web
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: navigatum
    deployment: web
  ports:
    - name: webclient
      port: 9000
      targetPort: 80
    - name: rendertron
      port: 9100
      targetPort: 3000
