apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigatum-maps
  labels:
    app: navigatum
    deployment: maps
  namespace: navigatum
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: navigatum
      deployment: maps
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: navigatum
        deployment: maps
    spec:
      volumes:
        - name: tmp-tileserver
          emptyDir: {}
        - name: navigatum-tileserver-vol
          persistentVolumeClaim:
              readOnly: false
              claimName: navigatum-tileserver-pvc
      containers:
        - name: tileserver
          image: maptiler/tileserver-gl:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # changing the public_url also changes this port.
              name: tileserver
          args:
            - --public_url="/maps/" # we want this to live under /maps/
          volumeMounts:
            - mountPath: /tmp
              name: tmp-tileserver
            - mountPath: /data
              name: navigatum-tileserver-vol
          securityContext:
            readOnlyRootFilesystem: true
          #resources:
          #  requests:
          #    cpu: 30m
          #    memory: 500Mi
          #  limits:
          #    cpu: 1000m
          #    memory: 700Mi
          #livenessProbe:
          #  httpGet:
          #    path: /maps/health
          #    port: tileserver
          #  failureThreshold: 1
          #  periodSeconds: 1
          #startupProbe:
          #  httpGet:
          #    path: /maps/health
          #    port: tileserver
          #  failureThreshold: 60
          #  periodSeconds: 1
