apiVersion: apps/v1
kind: Deployment
metadata:
    name: navigatum-webclient
    labels:
        app: navigatum
        deployment: web
    namespace: navigatum
spec:
    replicas: 1
    selector:
        matchLabels:
            app: navigatum
            deployment: web
    template:
        metadata:
            labels:
                app: navigatum
                deployment: web
        spec:
            containers:
                - name: navigatum-webclient
                  image: ghcr.io/tum-dev/navigatum-webclient:main
                  imagePullPolicy: Always
                  envFrom:
                      - configMapRef:
                            name: navigatum-config
                  ports:
                      - containerPort: 80
                        hostPort: 8000
                        name: navigatum-web
                  resources:
                    requests:
                      cpu: 50m
                      memory: 200Mi
                    limits:
                      cpu: 150m
                      memory: 500Mi
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: navigatum-web
                      failureThreshold: 3
                      periodSeconds: 5
                  startupProbe:
                      httpGet:
                          path: /health
                          port: navigatum-web
                      failureThreshold: 60
                      periodSeconds: 1