name: Add a new Deployment if necessary

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: branch to target when adding a deployment
        type: string
      pr-number:
        required: false
        description: number of the PR to target when adding a deployment
        type: string
        default: ""
  workflow_call:
    inputs:
      branch:
        required: true
        description: branch to target when adding a deployment
        type: string
      pr-number:
        required: false
        description: number of the PR to target when adding a deployment
        type: string
        default: ""
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deployment
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: rm -f staging/pr-${{ github.event.inputs.pr-number }}.yaml
      - run: git add .
      - run: git commit -m "Add deployment for PR #${{ inputs.pr-number }}"
      - run: git push
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app sync navigatum-stagings --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}

