name: Create and publish the Docker images

on:
    push:
        branches:
            - 'main'
    workflow_dispatch:

permissions:
    contents: read
    packages: write
jobs:
  build-and-push-data:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_suffix: data
      context: ./data
      dockerfile: Dockerfile
    secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-push-server:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_suffix: server
      context: ./server
      dockerfile: Dockerfile.server
    secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-push-mieli-search:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_suffix: mieli-search
      context: ./server
      dockerfile: Dockerfile.mielesearch
    secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-push-webclient:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_suffix: webclient
      context: ./webclient
      dockerfile: Dockerfile
    secrets:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
