name: Create and publish the Docker images

on:
  push:
  workflow_dispatch:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      data: ${{ steps.filter.outputs.data_server }}
      server: ${{ steps.filter.outputs.data_server }}
      webclient: ${{ steps.filter.outputs.webclient }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # &github is a YAML anchor
          # the server is required in data, since apparently it is impossibly to schedule a job after another in GitHub
          filters: |
            github: &github
              - '.github/**'
            data_server:
              - *github
              - 'data/**'
              - 'server/**'
            webclient:
              - *github
              - 'webclient/**'
  data-build:
    needs:
      - changes
    if: ${{ needs.changes.outputs.data == 'true' }}
    uses: ./.github/workflows/docker-build.yml
    with:
      image_suffix: data
      context: ./data
      dockerfile: Dockerfile
    permissions:
      contents: read
      packages: write
  data-deployment:
    runs-on: ubuntu-latest
    needs:
      - data-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum restart --kind Deployment --resource-name navigatum-data --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
      - run: sleep 5
  server-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - data-deployment
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: server
      context: ./server
      dockerfile: Dockerfile.server
    permissions:
      contents: read
      packages: write
  mieli-search-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - data-deployment
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: mieli-search
      context: ./server
      dockerfile: Dockerfile.mielesearch
    permissions:
      contents: read
      packages: write
  server-deployment:
    name: "Restart Deployment navigatum-server"
    runs-on: ubuntu-latest
    needs:
      - server-build
      - mieli-search-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum restart --kind Deployment --resource-name navigatum-server --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
  webclient-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - changes
    if: ${{ needs.changes.outputs.webclient == 'true' }}
    with:
      image_suffix: webclient
      context: ./webclient
      dockerfile: Dockerfile
    permissions:
      contents: read
      packages: write
  webclient-deployment:
    name: "Restart Deployment navigatum-webclient"
    runs-on: ubuntu-latest
    needs:
      - webclient-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum restart --kind Deployment --resource-name navigatum-webclient --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
