name: Add a comment to new PRs

on:
  pull_request_target:
    branches: [main]
    types: [opened, reopened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            -X POST \
            ${{ github.event.pull_request.comments_url }} \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --data '{ "body": "👋 Thank you for contributing. A [staging environment for this PR](https://pr-${{ github.event.number }}.nav.tum.sexy) for this change will be available shortly" }'
