name: Remove a Deployment

on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deployment
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: rm -f staging/pr-${{ github.event.number }}.yaml
      - run: git add .
      - run: git commit -m "Removed the deployment for PR ${{ '#' }}${{ github.event.number }}"
      - run: git push
