name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      deployment:
        required: true
        description: Image to be deployed
        type: string

jobs:
  webclient-deployment:
    if: github.ref == 'refs/heads/main'
    name: "Restart Deployment navigatum-webclient"
    runs-on: ubuntu-latest
    steps:
      -   run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      -   run: argocd app actions run navigatum-prod restart --kind Deployment --resource-name webclient --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
  webclient-staging-deployment:
    if: github.ref != 'refs/heads/main'
    name: "Restart staging Deployment"
    runs-on: ubuntu-latest
    steps:
      -   run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      -   run: argocd app actions run pr-${{github.event.number}} restart --kind Deployment --resource-name webclient --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}