name: server CD

on:
  push:
  workflow_dispatch:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      server: ${{ steps.filter.outputs.server }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
              - '.github/**'
              - 'server/**'
  server-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: server
      context: ./server
      dockerfile: Dockerfile.server
    permissions:
      contents: read
      packages: write
  server-init-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: server-init
      context: ./server
      dockerfile: Dockerfile.dbinit
    permissions:
      contents: read
      packages: write
  mieli-search-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: mieli-search
      context: ./server
      dockerfile: Dockerfile.mielesearch
    permissions:
      contents: read
      packages: write
  api-tests:
    runs-on: ubuntu-20.04
    services:
      mieli:
        image: ghcr.io/tum-dev/navigatum-mieli-search:main
        # TODO get the tags from ${{ needs.mieli-search-build.outputs.tags }}
        ports:
          - 7700
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: 1.65
      # run project's dependencies
      - run: cargo build
        working-directory: server
      - run: cargo run &
        working-directory: server

      # Runs Schemathesis tests with all checks enabled
      - uses: schemathesis/action@v1
        with:
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}
          api-name: navigatum
          schema: "./openapi.yaml"
          base-url: "http://localhost:8080"
          args: "--endpoint='/api/[^f].*'" # disable the feedbacks endpoint
  server-deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - server-build
      - server-init-build
      - mieli-search-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum-prod restart --kind Deployment --resource-name server --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
  server-staging-deployment:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - server-build
      - server-init-build
      - mieli-search-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run pr-${{github.event.number}} restart --kind Deployment --resource-name server --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
