name: server CD

on:
  push:
  workflow_dispatch:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      data: ${{ steps.filter.outputs.data_server }}
      server: ${{ steps.filter.outputs.data_server }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # the server is required in data, since apparently it is impossibly to schedule a job after another in GitHub
          filters: |
            data_server:
              - '.github/**'
              - 'data/**'
              - 'server/**'
  data-build:
    needs:
      - changes
    if: ${{ needs.changes.outputs.data == 'true' }}
    uses: ./.github/workflows/docker-build.yml
    with:
      image_suffix: data
      context: ./data
      dockerfile: Dockerfile
    permissions:
      contents: read
      packages: write
  data-deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - data-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum restart --kind Deployment --resource-name navigatum-data --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
      - run: sleep 5
  server-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - data-deployment
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: server
      context: ./server
      dockerfile: Dockerfile.server
    permissions:
      contents: read
      packages: write
  mieli-search-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - data-deployment
      - changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    with:
      image_suffix: mieli-search
      context: ./server
      dockerfile: Dockerfile.mielesearch
    permissions:
      contents: read
      packages: write
  api-tests:
    runs-on: ubuntu-20.04
    services:
      mieli:
        image: ghcr.io/tum-dev/navigatum-mieli-search:main
        # TODO get the tags from ${{ needs.mieli-search-build.outputs.tags }}
        ports:
          - 7700
    steps:
      -   uses: actions/checkout@v3.0.0
      -   uses: ATiltedTree/setup-rust@v1.0.5

      # run project's dependencies
      -   run: cd server && cargo build && cargo run &

      # Runs Schemathesis tests with all checks enabled
      -   uses: schemathesis/action@v1
          with:
            token: ${{ secrets.SCHEMATHESIS_TOKEN }}
            schema: './openapi.json'
            base-url: 'http://localhost:8080'
            args: "--endpoint='/api/[^f].*'" # disable the feedbacks endpoint
  server-deployment:
    if: github.ref == 'refs/heads/main'
    name: "Restart Deployment navigatum-server"
    runs-on: ubuntu-latest
    needs:
      - server-build
      - mieli-search-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum restart --kind Deployment --resource-name navigatum-server --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
