name: webclient CD

on:
  push:
  workflow_dispatch:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      webclient: ${{ steps.filter.outputs.webclient }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            webclient:
              - '.github/**'
              - 'webclient/**'
  webclient-build:
    uses: ./.github/workflows/docker-build.yml
    needs:
      - changes
    if: ${{ needs.changes.outputs.webclient == 'true' }}
    with:
      image_suffix: webclient
      context: ./webclient
      dockerfile: Dockerfile
    permissions:
      contents: read
      packages: write
  webclient-deployment:
    if: github.ref == 'refs/heads/main'
    name: "Restart Deployment navigatum-webclient"
    runs-on: ubuntu-latest
    needs:
      - webclient-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run navigatum-prod restart --kind Deployment --resource-name webclient --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
  webclient-staging-deployment:
    if: github.ref != 'refs/heads/main'
    name: "Restart staging Deployment"
    runs-on: ubuntu-latest
    needs:
      - webclient-build
    steps:
      - run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd
      - run: argocd app actions run pr-${{github.event.number}} restart --kind Deployment --resource-name webclient --auth-token ${{ secrets.ARGOCD_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
